### ISSUE TITLE
啥时候更新一下？

### ISSUE THREAD

**Issue by onedaydayde** [Steven-Fake/JavBus-forum-mobile-layout#2]
啥时候更新一下？
列表页的图片超出显示
还有内容页的文字超出显示

**Comment by Steven-Fake** [comment]
> 啥时候更新一下？
> 列表页的图片超出显示
> 还有内容页的文字超出显示

- 前段时间比较忙没上过论坛，确实做的还不够完善。近期会更新一下，修复一些我已发现的问题。
- 能否提供一下出现上述问题的页面链接？我会尽快进行对应的调整。
