### ISSUE TITLE
子版块页面显示不正常

### ISSUE THREAD

**Issue by TscCai** [Steven-Fake/JavBus-forum-mobile-layout#3]
**描述：**
以此链接为例：/forum/forum.php?mod=forumdisplay&fid=2，下同。

1. 脚本没有针对url中包含"fid="的情况进行单独处理，导致进入了index的逻辑。在执行到第199行时（此为1.2.0版本中的行号，1.1.3中仍存在该问题），浏览器报postListContainer.style对象undefined。而在iOS的via浏览器中遇到空指针、undefined等异常就直接中止运行，界面上是一片空白。
2. 在从帖子页面返回到子版块后，脚本的第66行（1.1.3版），错误地执行了```document.getElementsByClassName("wp cl")[0].remove();```导致帖子列表所在的div被整个从DOM树中移除。该问题我没有验证是否存在于1.2.0版。

**采取的措施：**
我修改了1.1.3版本的代码，使得脚本能在via浏览器中正常运行，但在上述链接中，每个帖子的标题由于过长而又没有自动换行，比较影响阅读，暂时将标题部分的<a>设置了宽度40%。
修改后的代码如下：
[JavBus-forum-mobile-layout.user-1.1.3+.zip](https://github.com/user-attachments/files/16216400/JavBus-forum-mobile-layout.user-1.1.3%2B.zip)

**环境：**
JavBus-forum-mobile-layout版本：1.1.3
via浏览器版本：1.4.7（28）

**Comment by Steven-Fake** [comment]
已定位到错误，将会尽快在下个版本修复。

**Comment by Steven-Fake** [comment]
现在已经将1.3版本推送到Sleazyfork上了，Android设备上可以正常使用，但我没有iOS设备，所以这方面的表现不是很清楚，可以抽空体验一下。如果没问题了就关掉issue吧

**Comment by TscCai** [comment]
已更新，页面显示正常。但有一个小问题，我这里的via浏览器必须要在metadata里显示声明run-at，否则脚本不会执行。经我测试，取值为```document-body```，```document-start```，```document-idle```均可。

**Comment by Steven-Fake** [comment]
> 已更新，页面显示正常。但有一个小问题，我这里的via浏览器必须要在metadata里显示声明run-at，否则脚本不会执行。经我测试，取值为```document-body```，```document-start```，```document-idle```均可。

- 根据 [文档](https://www.tampermonkey.net/documentation.php#meta:run_at) 中的描述，在未提供`@run_at`时，该项默认值为`document-idle`。
- 我先前在安卓版via中测试时是正常的，但考虑到via是自行实现的脚本管理器，以及是调用系统WebKit/WebView的，这种情况也确实有可能。
- 反正这条规则也符合规范，今天晚些时候会更个小版本，把这一条加上，感谢反馈。
