### ISSUE TITLE
iOS via浏览器中元素被异常删除

### ISSUE THREAD

**Issue by TscCai** [Steven-Fake/JavBus-forum-mobile-layout#4]
对，我又来了。
这次发现的第一个问题是这样：我在帖子页面浏览了一个帖子后，点击后退按钮，或者直接左滑后退至子版块页面，帖子列表就被删除了。
我在脚本（1.3.1）的第178行之前添加了一行代码：
```js
// 临时增加的代码
alert("div id: "+document.querySelector("div.wp.cl").id);
// 2.删除本就隐藏的元素
document.querySelector("div.wp.cl")?.remove();
```
这个脚本在PC的移动端模式运行正常，```document.querySelector("div.wp.cl").id```函数得到的是一个空串。在后退时，脚本不会被执行，调试窗口中断点未命中。
但在iOS的via浏览器中，当从帖子页面浏览后返回上一级至子版块帖子列表页面时，弹出了对话框，并且```document.querySelector("div.wp.cl").id```得到的结果是```"ct"```，于是帖子列表被删除了。怀疑这是iOS系统或者WebView的一个bug：在后退时脚本会被再次执行一次。
目前我的处理方法是将
```js
document.querySelector("div.wp.cl")?.remove();
```
替换成
```js
document.querySelector("div.wp.cl:not([id='ct'])")?.remove();
```

但这还没完，当修改了上面的代码后，确实后退不再删除帖子列表了，但这时如果前进到帖子页面，帖子内容又被移除了。原因还是前进时脚本又执行了一次。经我验证这大概率是iOS的内存回收机制上的问题，即页面跳转之后就把原先页面占用的内存回收了。
若要修复，可能只有考虑检测拿到的div的innerHTML长度，大致看了下待删除的div的innerHTML长度是一个固定的且较小的值。不过即便不修复，影响也不大。

环境：
js脚本：1.3.1
via浏览器1.4.7
iOS：15.3.1

**Comment by Steven-Fake** [comment]
还是那个问题，我没有iOS设备，不太容易确定这个问题的成因....

我记得这行代码是删除一个不显示或者空的元素，只是该元素的宽度是个固定值。不删除的话实际内容还是符合手机尺寸的，但页面大小会因为该元素而被顶得很宽，存在大量的空白区域。如果不是太在意的话就直接注释掉吧
